---
#------------------- included templates -------------------#

include:
  - project: 'scaleflyt/devops/gitlab-templates/scaleflyt-core-gitlab-templates-pipelines'
    file: 'pipelines/core_backend_microservice_pipeline.gitlab-ci.yml'
    ref: ${REF_PIPELINE_MICROSERVICE}
  - project: 'scaleflyt/devops/gitlab-templates/scaleflyt-core-gitlab-templates-jobs'
    file: 'jobs/deploy_microservice.gitlab-ci.yml'
    ref: ${REF_JOB_MICROSERVICE}

#------------------- common variables -------------------#

variables:
  # Restart pod
  APP: trajectory-processing
  # Release name
  APP_NAME: core-trajectory-processing
  # Helm chart version
  CHART_VERSION: ${REF_CHART_MICROSERVICE}
  # Sonar settings
  SONAR_PROJECT_KEY: core-trajectory-processing
  SONAR_EXCLUDED_FILES: ',benchmark/**,profile/**,src/contingency/VisibilityGraph.ts,src/types.ts,jest.config.js,test/**'
