name: CI/CD

on:
  push:
    branches:
      - main
      - new/**
      - update/**
      - fix/**
      - init
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Setup and Cache
        id: cache
        uses: ./.github/actions/setup-node-with-cache

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: yarn install --frozen-lockfile

  build:
    needs: install
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v5

      - name: Setup and Cache
        uses: ./.github/actions/setup-node-with-cache

      - run: yarn build

      - uses: actions/upload-artifact@v7
        with:
          name: dist
          path: dist
          retention-days: 1

  lint:
    needs: build
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v5

      - name: Setup and Cache
        uses: ./.github/actions/setup-node-with-cache

      - run: yarn lint

  test:
    needs: build
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v5

      - name: Setup and Cache
        uses: ./.github/actions/setup-node-with-cache

      - run: yarn test

  release:
    needs: [build, lint, test]
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write
    steps:
      - uses: actions/checkout@v5

      - name: Setup and Cache
        uses: ./.github/actions/setup-node-with-cache

      - uses: actions/download-artifact@v7
        with:
          name: dist
          path: dist

      - run: yarn semantic-release
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
